# Optionally uncomment to ignore specific alerts
#alerts:
#  ignore-alerts:
#    - alertTypeMissedRecentBlocks

notifications:
  service: discord
  discord:
    webhook:
      id: DISCORD_WEBHOOK_ID
      token: DISCORD_WEBHOOK_TOKEN
    alert-user-ids:
      - DISCORD_USER_ID
    username: HalfLife
validators:
- name: Haqq
  rpc: https://haqq-t.rpc.manticore.team:443/
  address: BECH32_CONSVAL_ADDRESS
  chain-id: haqq_54211-2
  rpc-retries: 20
  # only alert when 2/20 missed blocks have occurred (default is 1)
  missed-blocks-threshold: 1
  # enable this when the node is not in the active set
  fullnode: true
